-- ============================================================================
--  WorkSpace Pro — 사내 통합 업무 포털  전체 데이터베이스 (정리본 + 유지보수 가이드)
--  최종 갱신: 재고관리 / 담당자 UUID / 거래처·창고 / 발주·견적 확장컬럼 /
--             직급 옵션(taxonomy_options) / 작업·정비 완료 보고서(completion_reports) 반영.
-- ============================================================================
--
--  ▣ 이 파일은 두 가지 역할을 합니다.
--    1) 빈 Supabase 프로젝트에 통째로 실행하면 = 현재와 똑같은 구조가 만들어집니다.
--    2) 운영 중 DB에 다시 실행해도 = 데이터가 지워지지 않고 현재 상태로 맞춰집니다.
--       (모든 문장이 "있으면 두고 없으면 생성" 방식)
--
--  ▣ 실행 순서 주의: "(8) 실시간 등록"만 빼고 통째로 실행하세요.
--    이미 등록된 테이블을 다시 add 하면 오류(=정상, 이미 등록됨)가 나면서
--    트랜잭션 전체가 롤백됩니다. (8)은 아직 등록 안 한 테이블만 "한 줄씩" 따로
--    실행하고, already member 메시지는 무시하세요.
--
-- ════════════════════════════════════════════════════════════════════════════
--  ★ 유지보수 핵심 안내 (먼저 읽어주세요) ★
-- ════════════════════════════════════════════════════════════════════════════
--
--  ● 부서(dept_id)는 DB가 아니라 "프론트엔드 코드"에 정의돼 있습니다.
--    각 행의 dept_id 는 텍스트 코드(예: south_cs, strategy, hydrogen, rnd,
--    central_cs, sales, ceo)일 뿐입니다. 부서를 추가/이름변경하려면 HTML 파일의
--    STATE.departments 를 수정하세요(DB는 손댈 필요 없음).
--
--  ● 권한 규칙의 큰 틀 (전 테이블 공통)
--      - 읽기(SELECT)  : 승인된 직원 또는 관리자   → is_approved() or is_admin()
--      - 쓰기(I/U/D)   : 본인 부서 또는 관리자     → is_admin() or dept_id = my_dept()
--    이 규칙을 바꾸려면 아래 "(6) RLS 정책"의 해당 테이블 블록만 고치면 됩니다.
--
--  ● 새 기능 테이블을 추가하려면 → 맨 아래 "(9) 확장 템플릿"을 복사해 테이블명만
--    바꿔 실행하면 부서 권한 + 실시간까지 한 번에 셋업됩니다.
--
-- ============================================================================


-- ----------------------------------------------------------------------------
-- (1) 스토리지 버킷  ── 첨부파일 저장소
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do update set public = false;


-- ----------------------------------------------------------------------------
-- (2) 테이블 정의
-- ----------------------------------------------------------------------------

-- (2-A) profiles : 임직원 계정/권한 원장 (auth.users 와 1:1) ------------------
create table if not exists public.profiles (
    id         uuid primary key references auth.users(id) on delete cascade,
    email      text,
    name       text,
    dept_id    text,
    role       text default 'employee',
    position   text,
    approved   boolean default false,
    created_at timestamptz default now()
);

-- (2-B) events : 캘린더 일정 -------------------------------------------------
create table if not exists public.events (
    id         bigint generated by default as identity primary key,
    title      text,
    dept_id    text,
    start_date date,
    end_date   date,
    site       text,
    created_at timestamptz default now()
);

-- (2-C) projects : 프로젝트(과제) 관리 --------------------------------------
create table if not exists public.projects (
    id         bigint generated by default as identity primary key,
    title      text,
    dept_id    text,
    status     text default 'ongoing',
    start_date date,
    end_date   date,
    progress   int  default 0,
    descr      text,
    items      jsonb default '[]'::jsonb,
    created_at timestamptz default now()
);

-- (2-D) documents : 통합 보고 허브(전자결재) ---------------------------------
create table if not exists public.documents (
    id            bigint generated by default as identity primary key,
    title         text,
    dept_id       text,
    author        text,
    doc_date      date,
    file_type     text,
    file_size     text,
    storage_path  text,
    file_mime     text,
    status        text default 'approved',
    reject_reason text,
    approver      text,
    approved_at   timestamptz,
    approvers     jsonb default '[]'::jsonb,
    viewers       jsonb default '[]'::jsonb,
    created_at    timestamptz default now()
);

-- (2-E) weekly_meetings : 주간 업무 보고 ------------------------------------
create table if not exists public.weekly_meetings (
    id           bigint generated by default as identity primary key,
    dept_id      text,
    week         text,
    author       text,
    meet_date    date,
    content      text,
    image        text,
    file_name    text,
    file_path    text,
    file_mime    text,
    title        text,
    decisions    text,
    action_items text,
    next_plan    text,
    days         jsonb default '[]'::jsonb,
    created_at   timestamptz default now()
);

-- (2-F) app_settings : 전사 설정(키-값) -------------------------------------
create table if not exists public.app_settings (
    key   text primary key,
    value jsonb
);

-- (2-G) sites : 현장(고객사 현장) 목록 --------------------------------------
create table if not exists public.sites (
    id         bigint generated by default as identity primary key,
    name       text,
    created_at timestamptz default now()
);

-- (2-H) tickets : 현장 지원 / AS 티켓 ---------------------------------------
create table if not exists public.tickets (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    updated_at  timestamptz default now(),
    customer    text,
    site        text,
    equipment   text,
    issue       text,
    urgency     text default 'normal',
    assignee    text,
    status      text default 'received',
    result      text,
    dept_id     text,
    author      text,
    photos      jsonb default '[]'::jsonb,
    assignee_id text
);
alter table public.tickets add column if not exists assignee_id text;

-- (2-I) assets : 설비 자산 대장 + 정기점검(PM) ------------------------------
create table if not exists public.assets (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    name        text,
    model       text,
    customer    text,
    site        text,
    pm_cycle    int  default 0,
    last_pm     date,
    notes       text,
    assignee    text,
    position    text,
    dept_id     text,
    assignee_id text
);
alter table public.assets add column if not exists assignee    text;
alter table public.assets add column if not exists position    text;
alter table public.assets add column if not exists dept_id     text;
alter table public.assets add column if not exists assignee_id text;

-- (2-J) audit_logs : 보안 감사 원장 -----------------------------------------
create table if not exists public.audit_logs (
    id          bigint generated by default as identity primary key,
    created_at  timestamptz default now(),
    actor       text,
    actor_email text,
    action      text,
    target      text,
    detail      text
);

-- (2-K) inventory_items : 재고 품목 마스터 ----------------------------------
create table if not exists public.inventory_items (
    id         bigint generated by default as identity primary key,
    sku        text,
    name       text,
    category   text,
    unit       text default 'EA',
    stock      numeric default 0,
    safe_stock numeric default 0,
    unit_price numeric default 0,
    supplier   text,
    location   text,
    dept_id    text,
    notes      text,
    created_at timestamptz default now()
);

-- (2-L) stock_moves : 입출고 이력 -------------------------------------------
create table if not exists public.stock_moves (
    id            bigint generated by default as identity primary key,
    item_id       bigint references public.inventory_items(id) on delete cascade,
    kind          text,
    qty           numeric,
    reason        text,
    actor         text,
    actor_id      uuid,
    dept_id       text,
    balance_after numeric,
    created_at    timestamptz default now()
);

-- (2-M) inventory_options : 재고 기준정보(드롭다운 옵션) ---------------------
create table if not exists public.inventory_options (
    id         bigint generated by default as identity primary key,
    kind       text not null,
    value      text not null,
    code       text,
    created_at timestamptz default now()
);


-- ----------------------------------------------------------------------------
-- (3) 함수 (권한 판별 + 계정 자동화)
-- ----------------------------------------------------------------------------
create or replace function public.is_admin()
    returns boolean language sql stable security definer set search_path = public as $$
    select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create or replace function public.my_dept()
    returns text language sql stable security definer set search_path = public as $$
    select dept_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_approved()
    returns boolean language sql stable security definer set search_path = public as $$
    select exists (select 1 from public.profiles where id = auth.uid() and coalesce(approved,false) = true);
$$;

create or replace function public.handle_new_user()
    returns trigger language plpgsql security definer set search_path = public as $$
declare first_user boolean;
begin
    select count(*) = 0 into first_user from public.profiles;
    insert into public.profiles (id, email, name, position, dept_id, role, approved)
    values (
        new.id, new.email,
        coalesce(new.raw_user_meta_data->>'name', ''),
        coalesce(new.raw_user_meta_data->>'position', ''),
        coalesce(new.raw_user_meta_data->>'dept_id', 'strategy'),
        case when first_user then 'admin' else 'employee' end,
        case when first_user then true  else false      end
    );
    return new;
end; $$;

create or replace function public.protect_profile_fields()
    returns trigger language plpgsql security definer set search_path = public as $$
begin
    if not public.is_admin() then
        new.role     := old.role;
        new.approved := old.approved;
        new.dept_id  := old.dept_id;
    end if;
    return new;
end; $$;


-- ----------------------------------------------------------------------------
-- (4) 트리거
-- ----------------------------------------------------------------------------
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute function public.handle_new_user();

drop trigger if exists trg_protect_profile on public.profiles;
create trigger trg_protect_profile
    before update on public.profiles
    for each row execute function public.protect_profile_fields();


-- ----------------------------------------------------------------------------
-- (5) 행 수준 보안(RLS) 활성화
-- ----------------------------------------------------------------------------
alter table public.profiles          enable row level security;
alter table public.events            enable row level security;
alter table public.projects          enable row level security;
alter table public.documents         enable row level security;
alter table public.weekly_meetings   enable row level security;
alter table public.app_settings      enable row level security;
alter table public.sites             enable row level security;
alter table public.tickets           enable row level security;
alter table public.assets            enable row level security;
alter table public.audit_logs        enable row level security;
alter table public.inventory_items   enable row level security;
alter table public.stock_moves       enable row level security;
alter table public.inventory_options enable row level security;


-- ----------------------------------------------------------------------------
-- (6) RLS 정책  ── 누가 무엇을 읽고/쓸 수 있는가
-- ----------------------------------------------------------------------------

-- (6-A) profiles
drop policy if exists profiles_sel on public.profiles;
create policy profiles_sel on public.profiles for select to authenticated
    using (is_admin() or id = auth.uid() or (is_approved() and coalesce(approved,false) = true));
drop policy if exists profiles_ins on public.profiles;
create policy profiles_ins on public.profiles for insert to authenticated with check (id = auth.uid());
drop policy if exists profiles_upd on public.profiles;
create policy profiles_upd on public.profiles for update to authenticated
    using (is_admin() or id = auth.uid()) with check (is_admin() or id = auth.uid());
drop policy if exists profiles_del on public.profiles;
create policy profiles_del on public.profiles for delete to authenticated using (is_admin());

-- (6-B) 부서 기반 테이블(events/projects/weekly_meetings/tickets/assets/inventory_items)
do $$
declare t text;
begin
    foreach t in array array['events','projects','weekly_meetings','tickets','assets','inventory_items'] loop
        execute format('drop policy if exists %I_sel on public.%I', t, t);
        execute format('create policy %I_sel on public.%I for select to authenticated using (is_approved() or is_admin())', t, t);
        execute format('drop policy if exists %I_ins on public.%I', t, t);
        execute format('create policy %I_ins on public.%I for insert to authenticated with check (is_admin() or dept_id = my_dept())', t, t);
        execute format('drop policy if exists %I_upd on public.%I', t, t);
        execute format('create policy %I_upd on public.%I for update to authenticated using (is_admin() or dept_id = my_dept()) with check (is_admin() or dept_id = my_dept())', t, t);
        execute format('drop policy if exists %I_del on public.%I', t, t);
        execute format('create policy %I_del on public.%I for delete to authenticated using (is_admin() or dept_id = my_dept())', t, t);
    end loop;
end $$;

-- (6-C) documents
drop policy if exists documents_sel on public.documents;
create policy documents_sel on public.documents for select to authenticated using (is_approved() or is_admin());
drop policy if exists documents_ins on public.documents;
create policy documents_ins on public.documents for insert to authenticated with check (is_admin() or dept_id = my_dept());
drop policy if exists documents_upd on public.documents;
create policy documents_upd on public.documents for update to authenticated
    using (is_admin() or dept_id = my_dept() or exists (
        select 1 from jsonb_array_elements(coalesce(approvers,'[]'::jsonb)) e where (e->>'id') = auth.uid()::text))
    with check (true);
drop policy if exists documents_del on public.documents;
create policy documents_del on public.documents for delete to authenticated using (is_admin() or dept_id = my_dept());

-- (6-D) sites / inventory_options : 공용 기준정보
do $$
declare t text;
begin
    foreach t in array array['sites','inventory_options'] loop
        execute format('drop policy if exists %I_sel on public.%I', t, t);
        execute format('create policy %I_sel on public.%I for select to authenticated using (is_approved() or is_admin())', t, t);
        execute format('drop policy if exists %I_ins on public.%I', t, t);
        execute format('create policy %I_ins on public.%I for insert to authenticated with check (is_approved() or is_admin())', t, t);
        execute format('drop policy if exists %I_upd on public.%I', t, t);
        execute format('create policy %I_upd on public.%I for update to authenticated using (is_approved() or is_admin()) with check (is_approved() or is_admin())', t, t);
        execute format('drop policy if exists %I_del on public.%I', t, t);
        execute format('create policy %I_del on public.%I for delete to authenticated using (is_approved() or is_admin())', t, t);
    end loop;
end $$;

-- (6-E) app_settings
drop policy if exists app_settings_sel on public.app_settings;
create policy app_settings_sel on public.app_settings for select to authenticated using (is_approved() or is_admin());
drop policy if exists app_settings_ins on public.app_settings;
create policy app_settings_ins on public.app_settings for insert to authenticated with check (is_admin());
drop policy if exists app_settings_upd on public.app_settings;
create policy app_settings_upd on public.app_settings for update to authenticated using (is_admin()) with check (is_admin());
drop policy if exists app_settings_del on public.app_settings;
create policy app_settings_del on public.app_settings for delete to authenticated using (is_admin());

-- (6-F) audit_logs : 기록=승인자 / 조회=관리자만
drop policy if exists audit_ins on public.audit_logs;
create policy audit_ins on public.audit_logs for insert to authenticated with check (is_approved());
drop policy if exists audit_sel on public.audit_logs;
create policy audit_sel on public.audit_logs for select to authenticated using (is_admin());

-- (6-G) stock_moves : 조회=승인자 / 입력=본인 부서 또는 관리자 / 수정·삭제 없음
drop policy if exists stock_moves_sel on public.stock_moves;
create policy stock_moves_sel on public.stock_moves for select to authenticated using (is_approved() or is_admin());
drop policy if exists stock_moves_ins on public.stock_moves;
create policy stock_moves_ins on public.stock_moves for insert to authenticated with check (is_admin() or dept_id = my_dept());


-- ----------------------------------------------------------------------------
-- (7) 스토리지(첨부파일) 보안 정책  ── 'documents' 버킷
-- ----------------------------------------------------------------------------
drop policy if exists doc_obj_select on storage.objects;
create policy doc_obj_select on storage.objects for select to authenticated
    using (bucket_id = 'documents' and (is_approved() or is_admin()));
drop policy if exists doc_obj_insert on storage.objects;
create policy doc_obj_insert on storage.objects for insert to authenticated
    with check (bucket_id = 'documents' and (is_approved() or is_admin()));
drop policy if exists doc_obj_update on storage.objects;
create policy doc_obj_update on storage.objects for update to authenticated
    using      (bucket_id = 'documents' and (owner = auth.uid() or is_admin()))
    with check (bucket_id = 'documents' and (owner = auth.uid() or is_admin()));
drop policy if exists doc_obj_delete on storage.objects;
create policy doc_obj_delete on storage.objects for delete to authenticated
    using (bucket_id = 'documents' and (owner = auth.uid() or is_admin()));


-- ----------------------------------------------------------------------------
-- (7-1) trade_documents : 발주 / 견적
-- ----------------------------------------------------------------------------
create table if not exists public.trade_documents (
  id              bigint generated by default as identity primary key,
  kind            text,                       -- 'po'(발주서) | 'quote'(견적서)
  doc_no          text,                       -- 자동 생성 문서번호
  partner         text,                       -- 거래처/고객사
  partner_contact text,
  doc_date        date,
  due_date        date,
  status          text default 'draft',       -- draft(작성)/issued(발행)/done(완료)
  items           jsonb default '[]'::jsonb,  -- 품목 명세
  vat             boolean default false,
  subtotal        numeric default 0,
  tax             numeric default 0,
  total           numeric default 0,
  notes           text,
  author          text,
  author_id       uuid,
  dept_id         text,
  created_at      timestamptz default now()
);
alter table public.trade_documents enable row level security;

drop policy if exists trade_documents_sel on public.trade_documents;
create policy trade_documents_sel on public.trade_documents for select to authenticated using (is_approved() or is_admin());
drop policy if exists trade_documents_ins on public.trade_documents;
create policy trade_documents_ins on public.trade_documents for insert to authenticated with check (is_admin() or dept_id = my_dept());
drop policy if exists trade_documents_upd on public.trade_documents;
create policy trade_documents_upd on public.trade_documents for update to authenticated using (is_admin() or dept_id = my_dept()) with check (is_admin() or dept_id = my_dept());
drop policy if exists trade_documents_del on public.trade_documents;
create policy trade_documents_del on public.trade_documents for delete to authenticated using (is_admin() or dept_id = my_dept());

-- trade_documents 확장 컬럼 (있으면 두고 없으면 추가)
alter table public.trade_documents add column if not exists due_date         date;
alter table public.trade_documents add column if not exists client           text;
alter table public.trade_documents add column if not exists service          text;
alter table public.trade_documents add column if not exists pjt_title        text;
alter table public.trade_documents add column if not exists inq_no           text;
alter table public.trade_documents add column if not exists item_no          text;
alter table public.trade_documents add column if not exists person_in_charge text;
alter table public.trade_documents add column if not exists payment          text;
alter table public.trade_documents add column if not exists delivery         text;
alter table public.trade_documents add column if not exists terms            text;
alter table public.trade_documents add column if not exists validity         text;
alter table public.trade_documents add column if not exists issuer_tel       text;
alter table public.trade_documents add column if not exists issuer_fax       text;
alter table public.trade_documents add column if not exists issuer_email     text;
alter table public.trade_documents add column if not exists received_at      timestamptz;
alter table public.trade_documents add column if not exists remarks          jsonb default '[]'::jsonb;


-- ----------------------------------------------------------------------------
-- (7-2) 재고 입/출고 처리 함수 (창고·유형 인식형 최종본)
-- ----------------------------------------------------------------------------
-- 감사 로그용 컬럼/함수가 먼저 필요하므로 audit_row 정의 후 재정의합니다(아래 7-4).
create or replace function public.apply_stock_move(p_item_id bigint, p_kind text, p_qty numeric, p_reason text)
returns public.inventory_items
language plpgsql
security definer
set search_path = public
as $$
declare it public.inventory_items; newbal numeric;
begin
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be positive'; end if;
  select * into it from public.inventory_items where id = p_item_id for update;
  if not found then raise exception 'item not found'; end if;
  if not (public.is_admin() or it.dept_id = public.my_dept()) then raise exception 'forbidden'; end if;
  if p_kind = 'in'  then newbal := coalesce(it.stock,0) + p_qty;
  elsif p_kind = 'out' then newbal := coalesce(it.stock,0) - p_qty;
  else raise exception 'invalid kind'; end if;
  if newbal < 0 then raise exception 'insufficient stock'; end if;
  update public.inventory_items set stock = newbal where id = p_item_id;
  insert into public.stock_moves(item_id, kind, qty, reason, actor, actor_id, dept_id, balance_after)
    values (p_item_id, p_kind, p_qty, p_reason,
            (select name from public.profiles where id = auth.uid()),
            auth.uid(), it.dept_id, newbal);
  select * into it from public.inventory_items where id = p_item_id;
  return it;
end$$;
grant execute on function public.apply_stock_move(bigint, text, numeric, text) to authenticated;


-- ----------------------------------------------------------------------------
-- (7-3) 감사 로그 자동 기록 (트리거 → 서버만 기록, 위조 불가)
-- ----------------------------------------------------------------------------
alter table public.audit_logs add column if not exists actor_id uuid;

create or replace function public.audit_row()
returns trigger language plpgsql security definer set search_path = public as $$
declare j jsonb; lbl text; det text;
begin
  if (TG_OP = 'DELETE') then j := to_jsonb(OLD); else j := to_jsonb(NEW); end if;
  lbl := coalesce(j->>'name', j->>'title', j->>'doc_no', j->>'sku', j->>'value', j->>'key', '#' || coalesce(j->>'id',''));
  det := coalesce(j->>'dept_id', '');
  insert into public.audit_logs(actor, actor_email, actor_id, action, target, detail, created_at)
  values (
    (select name from public.profiles where id = auth.uid()),
    nullif(auth.jwt() ->> 'email', ''),
    auth.uid(),
    TG_TABLE_NAME || '_' || lower(TG_OP),
    lbl, det, now()
  );
  if (TG_OP = 'DELETE') then return OLD; else return NEW; end if;
end$$;

drop trigger if exists trg_audit on public.profiles;
create trigger trg_audit after insert or update or delete on public.profiles         for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.projects;
create trigger trg_audit after insert or update or delete on public.projects         for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.documents;
create trigger trg_audit after insert or update or delete on public.documents        for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.weekly_meetings;
create trigger trg_audit after insert or update or delete on public.weekly_meetings  for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.tickets;
create trigger trg_audit after insert or update or delete on public.tickets          for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.assets;
create trigger trg_audit after insert or update or delete on public.assets           for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.trade_documents;
create trigger trg_audit after insert or update or delete on public.trade_documents  for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.sites;
create trigger trg_audit after insert or update or delete on public.sites            for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.inventory_options;
create trigger trg_audit after insert or update or delete on public.inventory_options for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.app_settings;
create trigger trg_audit after insert or update or delete on public.app_settings     for each row execute function public.audit_row();
drop trigger if exists trg_audit on public.inventory_items;
create trigger trg_audit after insert or delete on public.inventory_items            for each row execute function public.audit_row();

-- 직접 기록 차단: 트리거(서버)만 기록 → 위조·누락 불가
drop policy if exists audit_ins on public.audit_logs;
create policy audit_ins on public.audit_logs for insert to authenticated with check (false);


-- ----------------------------------------------------------------------------
-- (7-4) 거래처(partners)
-- ----------------------------------------------------------------------------
create table if not exists public.partners (
  id bigint generated by default as identity primary key,
  name text not null,
  kind text default 'both',          -- both(공통)/client(고객사)/supplier(공급처)
  contact text, tel text, fax text, email text,
  address text, biz_no text, notes text,
  created_at timestamptz default now()
);
alter table public.partners enable row level security;
drop policy if exists partners_sel on public.partners;
create policy partners_sel on public.partners for select to authenticated using (is_approved() or is_admin());
drop policy if exists partners_ins on public.partners;
create policy partners_ins on public.partners for insert to authenticated with check (is_approved() or is_admin());
drop policy if exists partners_upd on public.partners;
create policy partners_upd on public.partners for update to authenticated using (is_approved() or is_admin()) with check (is_approved() or is_admin());
drop policy if exists partners_del on public.partners;
create policy partners_del on public.partners for delete to authenticated using (is_approved() or is_admin());

drop trigger if exists trg_audit on public.partners;
create trigger trg_audit after insert or update or delete on public.partners for each row execute function public.audit_row();


-- ----------------------------------------------------------------------------
-- (7-5) 창고(warehouses) + 창고별 재고(inventory_stock)
-- ----------------------------------------------------------------------------
create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  name text not null, code text, location text, notes text,
  created_at timestamptz default now()
);
alter table public.warehouses enable row level security;
drop policy if exists wh_sel on public.warehouses;
create policy wh_sel on public.warehouses for select to authenticated using (is_approved() or is_admin());
drop policy if exists wh_ins on public.warehouses;
create policy wh_ins on public.warehouses for insert to authenticated with check (is_approved() or is_admin());
drop policy if exists wh_upd on public.warehouses;
create policy wh_upd on public.warehouses for update to authenticated using (is_approved() or is_admin()) with check (is_approved() or is_admin());
drop policy if exists wh_del on public.warehouses;
create policy wh_del on public.warehouses for delete to authenticated using (is_approved() or is_admin());

create table if not exists public.inventory_stock (
  item_id bigint not null references public.inventory_items(id) on delete cascade,
  warehouse_id bigint not null references public.warehouses(id) on delete cascade,
  qty numeric not null default 0,
  primary key (item_id, warehouse_id)
);
alter table public.inventory_stock enable row level security;
drop policy if exists invstock_sel on public.inventory_stock;
create policy invstock_sel on public.inventory_stock for select to authenticated using (is_approved() or is_admin());
drop policy if exists invstock_ins on public.inventory_stock;
create policy invstock_ins on public.inventory_stock for insert to authenticated with check (false);
drop policy if exists invstock_upd on public.inventory_stock;
create policy invstock_upd on public.inventory_stock for update to authenticated using (false);
drop policy if exists invstock_del on public.inventory_stock;
create policy invstock_del on public.inventory_stock for delete to authenticated using (false);

-- 입출고 이력에 창고 컬럼
alter table public.stock_moves add column if not exists warehouse_id bigint;

-- 기본창고 생성 + 기존 재고 이관
insert into public.warehouses (name, code, location)
  select '기본창고','WH1','' where not exists (select 1 from public.warehouses);
insert into public.inventory_stock (item_id, warehouse_id, qty)
  select i.id, (select id from public.warehouses order by id limit 1), coalesce(i.stock,0)
  from public.inventory_items i
  where not exists (select 1 from public.inventory_stock s where s.item_id = i.id);

drop trigger if exists trg_audit on public.warehouses;
create trigger trg_audit after insert or update or delete on public.warehouses for each row execute function public.audit_row();


-- ----------------------------------------------------------------------------
-- (7-6) 입출고 유형(subtype) + 창고 인식형 apply_stock_move 최종본
-- ----------------------------------------------------------------------------
alter table public.stock_moves add column if not exists subtype text;

insert into public.inventory_options (kind, value) select 'move_in','구매입고'      where not exists (select 1 from public.inventory_options where kind='move_in'  and value='구매입고');
insert into public.inventory_options (kind, value) select 'move_in','반품입고'      where not exists (select 1 from public.inventory_options where kind='move_in'  and value='반품입고');
insert into public.inventory_options (kind, value) select 'move_in','기타입고'      where not exists (select 1 from public.inventory_options where kind='move_in'  and value='기타입고');
insert into public.inventory_options (kind, value) select 'move_out','판매·소비출고' where not exists (select 1 from public.inventory_options where kind='move_out' and value='판매·소비출고');
insert into public.inventory_options (kind, value) select 'move_out','폐기'         where not exists (select 1 from public.inventory_options where kind='move_out' and value='폐기');
insert into public.inventory_options (kind, value) select 'move_out','반품출고'      where not exists (select 1 from public.inventory_options where kind='move_out' and value='반품출고');
insert into public.inventory_options (kind, value) select 'move_out','기타출고'      where not exists (select 1 from public.inventory_options where kind='move_out' and value='기타출고');

drop function if exists public.apply_stock_move(bigint, text, numeric, text);
drop function if exists public.apply_stock_move(bigint, text, numeric, text, bigint);
create or replace function public.apply_stock_move(p_item_id bigint, p_kind text, p_qty numeric, p_reason text, p_warehouse_id bigint default null, p_subtype text default null)
returns public.inventory_items language plpgsql security definer set search_path = public as $$
declare it public.inventory_items; wid bigint; cur numeric; newqty numeric; total numeric;
begin
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be positive'; end if;
  select * into it from public.inventory_items where id = p_item_id for update;
  if not found then raise exception 'item not found'; end if;
  if not (public.is_admin() or it.dept_id = public.my_dept()) then raise exception 'forbidden'; end if;
  wid := p_warehouse_id;
  if wid is null then select id into wid from public.warehouses order by id limit 1; end if;
  if wid is null then raise exception 'no warehouse'; end if;
  select qty into cur from public.inventory_stock where item_id = p_item_id and warehouse_id = wid for update;
  if not found then cur := 0; insert into public.inventory_stock(item_id, warehouse_id, qty) values (p_item_id, wid, 0); end if;
  if p_kind = 'in' then newqty := cur + p_qty;
  elsif p_kind = 'out' then newqty := cur - p_qty;
  else raise exception 'invalid kind'; end if;
  if newqty < 0 then raise exception 'insufficient stock'; end if;
  update public.inventory_stock set qty = newqty where item_id = p_item_id and warehouse_id = wid;
  select coalesce(sum(qty),0) into total from public.inventory_stock where item_id = p_item_id;
  update public.inventory_items set stock = total where id = p_item_id;
  insert into public.stock_moves(item_id, kind, qty, reason, subtype, actor, actor_id, dept_id, warehouse_id, balance_after)
    values (p_item_id, p_kind, p_qty, p_reason, p_subtype, (select name from public.profiles where id = auth.uid()), auth.uid(), it.dept_id, wid, newqty);
  select * into it from public.inventory_items where id = p_item_id;
  return it;
end$$;
grant execute on function public.apply_stock_move(bigint, text, numeric, text, bigint, text) to authenticated;

-- 창고 간 재고 이동 함수
create or replace function public.transfer_stock(p_item_id bigint, p_from_wh bigint, p_to_wh bigint, p_qty numeric, p_reason text)
returns public.inventory_items language plpgsql security definer set search_path = public as $$
declare it public.inventory_items; cur numeric; fromq numeric; toq numeric; fname text; tname text;
begin
  if p_qty is null or p_qty <= 0 then raise exception 'qty must be positive'; end if;
  if p_from_wh = p_to_wh then raise exception 'same warehouse'; end if;
  select * into it from public.inventory_items where id = p_item_id for update;
  if not found then raise exception 'item not found'; end if;
  if not (public.is_admin() or it.dept_id = public.my_dept()) then raise exception 'forbidden'; end if;
  select name into fname from public.warehouses where id = p_from_wh;
  select name into tname from public.warehouses where id = p_to_wh;
  select qty into cur from public.inventory_stock where item_id = p_item_id and warehouse_id = p_from_wh for update;
  if not found or cur < p_qty then raise exception 'insufficient stock'; end if;
  fromq := cur - p_qty;
  update public.inventory_stock set qty = fromq where item_id = p_item_id and warehouse_id = p_from_wh;
  if exists (select 1 from public.inventory_stock where item_id = p_item_id and warehouse_id = p_to_wh) then
    update public.inventory_stock set qty = qty + p_qty where item_id = p_item_id and warehouse_id = p_to_wh returning qty into toq;
  else
    insert into public.inventory_stock(item_id, warehouse_id, qty) values (p_item_id, p_to_wh, p_qty) returning qty into toq;
  end if;
  insert into public.stock_moves(item_id, kind, qty, reason, actor, actor_id, dept_id, warehouse_id, balance_after)
    values (p_item_id, 'out', p_qty, coalesce(p_reason,'창고 이동') || ' → ' || coalesce(tname,''), (select name from public.profiles where id = auth.uid()), auth.uid(), it.dept_id, p_from_wh, fromq);
  insert into public.stock_moves(item_id, kind, qty, reason, actor, actor_id, dept_id, warehouse_id, balance_after)
    values (p_item_id, 'in', p_qty, coalesce(p_reason,'창고 이동') || ' ← ' || coalesce(fname,''), (select name from public.profiles where id = auth.uid()), auth.uid(), it.dept_id, p_to_wh, toq);
  update public.inventory_items set stock = (select coalesce(sum(qty),0) from public.inventory_stock where item_id = p_item_id) where id = p_item_id;
  select * into it from public.inventory_items where id = p_item_id;
  return it;
end$$;
grant execute on function public.transfer_stock(bigint, bigint, bigint, numeric, text) to authenticated;


-- ----------------------------------------------------------------------------
-- (7-7) 문서번호 채번 + 로고 버킷
-- ----------------------------------------------------------------------------
create table if not exists public.doc_counters (
  scope text primary key,
  seq   int not null default 0
);
alter table public.doc_counters enable row level security;

create or replace function public.next_trade_no(p_kind text)
returns text language plpgsql security definer set search_path = public as $$
declare
  v_pre   text := case when lower(coalesce(p_kind,'po')) = 'po' then 'PO' else 'QT' end;
  v_scope text := v_pre || '-' || to_char(now(), 'YYYYMM');
  v_seed  int;
  v_next  int;
begin
  select coalesce(max(substring(doc_no from char_length(v_scope) + 2)::int), 0)
    into v_seed
    from public.trade_documents
   where doc_no ~ ('^' || v_scope || '-[0-9]+$');
  insert into public.doc_counters(scope, seq) values (v_scope, v_seed)
  on conflict (scope) do nothing;
  update public.doc_counters set seq = seq + 1 where scope = v_scope returning seq into v_next;
  return v_scope || '-' || lpad(v_next::text, 4, '0');
end; $$;
grant execute on function public.next_trade_no(text) to authenticated;

insert into storage.buckets (id, name, public)
values ('branding', 'branding', true)
on conflict (id) do update set public = true;

drop policy if exists "branding read"   on storage.objects;
create policy "branding read"   on storage.objects for select using (bucket_id = 'branding');
drop policy if exists "branding insert" on storage.objects;
create policy "branding insert" on storage.objects for insert to authenticated with check (bucket_id = 'branding');
drop policy if exists "branding update" on storage.objects;
create policy "branding update" on storage.objects for update to authenticated using (bucket_id = 'branding') with check (bucket_id = 'branding');
drop policy if exists "branding delete" on storage.objects;
create policy "branding delete" on storage.objects for delete to authenticated using (bucket_id = 'branding');


-- ----------------------------------------------------------------------------
-- (7-8) taxonomy_options : 분류·직급 옵션 (편집 가능한 드롭다운)
-- ----------------------------------------------------------------------------
create table if not exists public.taxonomy_options (
  id bigint generated always as identity primary key,
  category text not null,             -- 예: 'position'(직급)
  value text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
alter table public.taxonomy_options enable row level security;
-- 읽기: 가입(로그인 전) 화면에서도 직급 선택지가 보이도록 공개 읽기 허용
drop policy if exists "taxonomy_read" on public.taxonomy_options;
create policy "taxonomy_read"  on public.taxonomy_options for select using (true);
-- 쓰기: 로그인된 사용자(관리자 UI에서만 호출)
drop policy if exists "taxonomy_write" on public.taxonomy_options;
create policy "taxonomy_write" on public.taxonomy_options for all to authenticated using (true) with check (true);

drop trigger if exists trg_audit on public.taxonomy_options;
create trigger trg_audit after insert or update or delete on public.taxonomy_options for each row execute function public.audit_row();


-- ----------------------------------------------------------------------------
-- (7-9) completion_reports : 작업·정비 완료 보고서 (편집·삭제 기본 포함)
-- ----------------------------------------------------------------------------
create table if not exists public.completion_reports (
  id bigint generated always as identity primary key,
  ticket_id bigint references public.tickets(id) on delete cascade,
  asset_id  bigint references public.assets(id)  on delete set null,
  work_date date,
  worker    text,
  work_type text,
  result    text,
  content   text,
  parts     text,
  dept_id   text,
  author    text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
alter table public.completion_reports enable row level security;
-- ★★★ 여기가 이전에 잘려 있던 곳 — 정책문을 끝까지 완성했습니다 ★★★
drop policy if exists "creport_read"  on public.completion_reports;
create policy "creport_read"  on public.completion_reports for select to authenticated using (is_approved() or is_admin());
drop policy if exists "creport_write" on public.completion_reports;
create policy "creport_write" on public.completion_reports for all to authenticated using (is_approved() or is_admin()) with check (is_approved() or is_admin());

drop trigger if exists trg_audit on public.completion_reports;
create trigger trg_audit after insert or update or delete on public.completion_reports for each row execute function public.audit_row();


-- ----------------------------------------------------------------------------
-- (8) 실시간(Realtime) 등록   ※ "따로" 실행하세요. already member 오류는 무시.
--     아직 등록 안 한 테이블만 한 줄씩 실행하는 것을 권장합니다. (주석 해제 후 실행)
-- ----------------------------------------------------------------------------
-- alter publication supabase_realtime add table public.profiles;
-- alter publication supabase_realtime add table public.events;
-- alter publication supabase_realtime add table public.projects;
-- alter publication supabase_realtime add table public.documents;
-- alter publication supabase_realtime add table public.weekly_meetings;
-- alter publication supabase_realtime add table public.app_settings;
-- alter publication supabase_realtime add table public.sites;
-- alter publication supabase_realtime add table public.tickets;
-- alter publication supabase_realtime add table public.assets;
-- alter publication supabase_realtime add table public.inventory_items;
-- alter publication supabase_realtime add table public.stock_moves;
-- alter publication supabase_realtime add table public.inventory_options;
-- alter publication supabase_realtime add table public.partners;
-- alter publication supabase_realtime add table public.warehouses;
-- alter publication supabase_realtime add table public.inventory_stock;
-- alter publication supabase_realtime add table public.trade_documents;
-- alter publication supabase_realtime add table public.taxonomy_options;
-- alter publication supabase_realtime add table public.completion_reports;


-- ----------------------------------------------------------------------------
-- (선택) 재고 단위 기본값 — 옵션이 비어 있을 때만 채움
-- ----------------------------------------------------------------------------
insert into public.inventory_options (kind, value)
select v.kind, v.value from (values ('unit','EA'),('unit','BOX'),('unit','kg'),('unit','SET')) v(kind, value)
where not exists (select 1 from public.inventory_options where kind = 'unit');

-- (선택) 직급 기본값 — taxonomy_options 의 position 이 비어 있을 때만 채움
insert into public.taxonomy_options (category, value, sort_order)
select v.category, v.value, v.ord
from (values ('position','대표이사',0),('position','부서장',1),('position','팀장',2),('position','사원',3)) v(category, value, ord)
where not exists (select 1 from public.taxonomy_options where category = 'position');


-- ============================================================================
--  (9) 확장 템플릿 ── 새 "부서 기반" 기능 테이블 추가용 (복사해서 사용)
-- ============================================================================
--  create table if not exists public.my_table (
--      id bigint generated by default as identity primary key,
--      title text, dept_id text,           -- ★ dept_id 필수
--      created_at timestamptz default now()
--  );
--  alter table public.my_table enable row level security;
--  drop policy if exists my_table_sel on public.my_table;
--  create policy my_table_sel on public.my_table for select to authenticated using (is_approved() or is_admin());
--  drop policy if exists my_table_ins on public.my_table;
--  create policy my_table_ins on public.my_table for insert to authenticated with check (is_admin() or dept_id = my_dept());
--  drop policy if exists my_table_upd on public.my_table;
--  create policy my_table_upd on public.my_table for update to authenticated using (is_admin() or dept_id = my_dept()) with check (is_admin() or dept_id = my_dept());
--  drop policy if exists my_table_del on public.my_table;
--  create policy my_table_del on public.my_table for delete to authenticated using (is_admin() or dept_id = my_dept());
--  alter publication supabase_realtime add table public.my_table;   -- (따로 실행)
-- ============================================================================
--  끝.
-- ============================================================================
