-- ============================================================================
-- WorkSpace Pro · 재고관리 고도화 1단계 (발주 연계 · 미착/입고 · 평균단가 · 회계재고)
-- Supabase SQL Editor 에서 1회 실행하세요. (기존 데이터는 그대로 유지됩니다)
-- 안전하게 여러 번 실행해도 되도록 모두 IF NOT EXISTS / OR REPLACE 로 작성했습니다.
-- ============================================================================

-- 1) 입고 이력 테이블 -----------------------------------------------------------
--    발주서(trade_documents) 라인별 실제 입고 1건 = 1행. 부분 입고를 누적 기록합니다.
create table if not exists public.po_receipts (
    id            bigint generated by default as identity primary key,
    trade_id      bigint,                         -- 발주서 id (trade_documents.id)
    line_idx      integer not null default 0,     -- 발주서 items 배열 내 라인 순번(서브항목 제외 기준)
    item_id       bigint,                         -- 입고 대상 재고품목 id (inventory_items.id)
    description   text,                            -- 입고 시점의 품목 설명(스냅샷)
    qty           numeric not null default 0,      -- 입고 수량
    unit_price    numeric not null default 0,      -- 입고 단가
    amount        numeric not null default 0,      -- 입고 금액(qty*unit_price) — 회계재고 판정 기준
    warehouse_id  bigint,                          -- 입고 창고
    received_at   timestamptz not null default now(),
    actor         text,
    actor_id      uuid,
    dept_id       text,
    created_at    timestamptz not null default now()
);
create index if not exists idx_po_receipts_trade on public.po_receipts (trade_id);
create index if not exists idx_po_receipts_item  on public.po_receipts (item_id);
alter table public.po_receipts enable row level security;
-- 로그인 사용자 전체 허용(앱 레벨에서 권한 제어). 조직 정책에 맞게 조정하세요.
drop policy if exists po_receipts_all on public.po_receipts;
create policy po_receipts_all on public.po_receipts
    for all to authenticated using (true) with check (true);

-- 2) 재고품목 평균단가 · 회계재고 컬럼 ------------------------------------------
alter table public.inventory_items add column if not exists in_qty_total    numeric not null default 0;  -- 누적 입고 수량
alter table public.inventory_items add column if not exists in_amount_total numeric not null default 0;  -- 누적 입고 금액
alter table public.inventory_items add column if not exists avg_price       numeric not null default 0;  -- 가중평균 단가(=in_amount_total/in_qty_total)
alter table public.inventory_items add column if not exists acct_flag       boolean not null default false; -- 회계재고 여부(현재 적용값)
alter table public.inventory_items add column if not exists acct_auto       boolean not null default false; -- 자동분류로 회계재고가 된 적이 있는지
alter table public.inventory_items add column if not exists acct_locked     boolean not null default false; -- 담당자가 수동 지정 → 자동분류가 덮어쓰지 않음

-- 3) 입고 기록 RPC : 이력 적재 + 가중평균 재계산 + 회계재고 자동분류(원자적) -------
--    재고 수량 반영은 기존 apply_stock_move(p_kind:='in') 를 그대로 사용하고,
--    이 함수는 "이력/단가/회계" 만 담당합니다. (단일 UPDATE 라 동시 입고에도 단가 경쟁조건 없음)
--    회계재고 자동분류 기준: 입고 1건 금액 >= 1,000,000 (관리자/회계팀이 수동 잠금하면 유지)
create or replace function public.record_po_receipt(
    p_trade_id     bigint,
    p_line_idx     integer,
    p_item_id      bigint,
    p_qty          numeric,
    p_unit_price   numeric,
    p_warehouse_id bigint default null,
    p_description  text default null,
    p_actor        text default null,
    p_actor_id     uuid default null,
    p_dept_id      text default null
) returns public.inventory_items
language plpgsql
security definer
as $$
declare
    v_amount numeric := coalesce(p_qty,0) * coalesce(p_unit_price,0);
    v_item   public.inventory_items;
begin
    insert into public.po_receipts (trade_id, line_idx, item_id, description, qty, unit_price, amount, warehouse_id, actor, actor_id, dept_id)
    values (p_trade_id, coalesce(p_line_idx,0), p_item_id, p_description, coalesce(p_qty,0), coalesce(p_unit_price,0), v_amount, p_warehouse_id, p_actor, p_actor_id, p_dept_id);

    update public.inventory_items i set
        in_qty_total    = coalesce(i.in_qty_total,0)    + coalesce(p_qty,0),
        in_amount_total = coalesce(i.in_amount_total,0) + v_amount,
        avg_price       = case when (coalesce(i.in_qty_total,0) + coalesce(p_qty,0)) > 0
                               then (coalesce(i.in_amount_total,0) + v_amount) / (coalesce(i.in_qty_total,0) + coalesce(p_qty,0))
                               else 0 end,
        acct_auto       = case when v_amount >= 1000000 then true else coalesce(i.acct_auto,false) end,
        acct_flag       = case when v_amount >= 1000000 and not coalesce(i.acct_locked,false) then true else coalesce(i.acct_flag,false) end
    where i.id = p_item_id
    returning i.* into v_item;

    return v_item;
end;
$$;

-- 4) 회계재고 수동 지정/해제 RPC (담당자 추가/제외) -----------------------------
--    수동 지정 시 acct_locked=true 로 잠가 이후 자동분류가 값을 덮어쓰지 않게 합니다.
create or replace function public.set_inventory_acct(
    p_item_id bigint,
    p_flag    boolean
) returns public.inventory_items
language plpgsql
security definer
as $$
declare v_item public.inventory_items;
begin
    update public.inventory_items i set
        acct_flag   = p_flag,
        acct_locked = true
    where i.id = p_item_id
    returning i.* into v_item;
    return v_item;
end;
$$;

grant execute on function public.record_po_receipt(bigint,integer,bigint,numeric,numeric,bigint,text,text,uuid,text) to authenticated;
grant execute on function public.set_inventory_acct(bigint,boolean) to authenticated;

-- (실시간) po_receipts 를 supabase_realtime 발행에 등록 — 입고 발생 시 즉시 반영.
--   이미 등록돼 있으면 무시(멱등).
do $$ begin
  alter publication supabase_realtime add table public.po_receipts;
exception when duplicate_object then null; when undefined_object then null; end $$;

-- ============================================================================
-- 완료. 앱은 이 테이블/함수가 없으면 관련 화면을 자동으로 비활성화하므로,
-- 실행 전에도 기존 기능은 그대로 동작합니다.
-- ============================================================================
